services:
  dataset_server:
    build: ./dataset
    container_name: dataset
    image: emnist_data_gen:${FED_VERSION}
    cpus: ${DATASET_CPUS}
    volumes:
      - emnist_dataset
    ports:
      - ${DATASET_SERVER_PORT}:${DATASET_SERVER_PORT}
    networks:
      - fed_learning

  cpu_clients:
    build: ./clients
    deploy: 
      mode: replicated
      replicas: ${CLIENT_CPU_REPLICAS}
    image: emnist_client_cpu:${FED_VERSION}
    cpus: ${CLIENT_CPUS}
    depends_on:
      - dataset_server
      - agg_server
    networks:
      - fed_learning

  gpu_clients:
    build: ./clients
    deploy:
      mode: replicated
      replicas: ${CLIENT_GPU_REPLICAS}
    image: emnist_client_cpu:${FED_VERSION}
    cpus: ${CLIENT_CPUS}
    gpus: all
    depends_on:
      - dataset_server
      - agg_server
    networks:
      - fed_learning

  agg_server:
    build: ./server
    container_name: emnist_server
    image: emnist_server:${FED_VERSION}
    cpus: ${AGG_SERVER_CPUS}
    --networks:
      - fed_learning
    --ports:
      - ${AGG_SERVER_PORT}:${AGG_SERVER_PORT}
    
volumes:
- emnist_dataset

networks:
-  fed_learning