services:
  dataset_server:
    build:
      context: ./dataset
    container_name: dataset
    image: emnist_data_gen:${FED_VERSION}
    cpus: ${DATASET_CPUS}
    stop_grace_period: 1m
    volumes:
      - emnist_dataset:/workspace/datasets
    ports:
      - ${DATASET_SERVER_PORT}:${DATASET_SERVER_PORT}
    networks:
      - fed

  cpu_clients:
    build:
      context: ./client
    deploy: 
      mode: replicated
      replicas: ${CLIENT_CPU_REPLICAS}
    image: emnist_client:${FED_VERSION}
    cpus: ${CLIENT_CPUS}
    stop_grace_period: 1m
    depends_on:
      - dataset_server
      - agg_server
    networks:
      - fed

  gpu_clients:
    build:
      context: ./client
    deploy:
      mode: replicated
      replicas: ${CLIENT_GPU_REPLICAS}
    image: emnist_client:${FED_VERSION}
    cpus: ${CLIENT_CPUS}
    gpus: all
    stop_grace_period: 1m
    depends_on:
      - dataset_server
      - agg_server
    networks:
      - fed

  agg_server:
    build:
      context: ./server
    container_name: emnist_server
    image: emnist_server:${FED_VERSION}
    cpus: ${AGG_SERVER_CPUS}
    stop_grace_period: 1m
    networks:
      - fed
      - local
    ports:
      - ${AGG_SERVER_PORT}:${AGG_SERVER_PORT}
      - ${MLFLOW_SERVER_PORT}:${MLFLOW_SERVER_PORT}
volumes:
  emnist_dataset:
    external: true

networks:
  fed:
    name: fed
  local:
    name: local
    driver: bridge